# Generated by Django 5.1.2 on 2025-03-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('availability', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('space_type', models.CharField(max_length=100)),
                ('feature', models.CharField(max_length=100)),
                ('operating_hours', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parking_images/')),
                ('slot_quantity', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('rentperday', models.IntegerField(blank=True, null=True)),
                ('recurringquantity', models.IntegerField(blank=True, null=True)),
                ('total_slot', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField()),
                ('space_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('slot', models.IntegerField()),
                ('time', models.IntegerField(blank=True, null=True)),
                ('timei', models.TimeField(auto_now_add=True, null=True)),
                ('endtime', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='recurring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('availability', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('space_type', models.CharField(max_length=100)),
                ('feature', models.CharField(max_length=100)),
                ('operating_hours', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parking_images/')),
                ('area_email', models.EmailField(max_length=100)),
                ('slot_quantity', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('recurringquantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='applied', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('availability', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('space_type', models.CharField(blank=True, max_length=100, null=True)),
                ('feature', models.CharField(blank=True, max_length=100, null=True)),
                ('operating_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_information', models.IntegerField(blank=True, null=True)),
                ('area_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('slot_quantity', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('carname', models.CharField(max_length=200)),
                ('brandname', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('idproof', models.ImageField(blank=True, null=True, upload_to='idproof_images/')),
                ('time', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('carnumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('slot', models.IntegerField()),
                ('tser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carapp.add_areas')),
            ],
        ),
        migrations.CreateModel(
            name='Slotfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.add_areas')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('order_id', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.add_areas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='icart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.add_areas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.add_areas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='YTRExtrapay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tamount', models.IntegerField(blank=True, null=True)),
                ('Ttime', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('paid', 'Paid'), ('failed', 'Failed'), ('Pending', 'pending')], default='Pending', max_length=10, null=True)),
                ('Tpay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.pay')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carapp.user_reg')),
            ],
        ),
    ]
