# Generated by Django 5.1.2 on 2025-03-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytrextrapay',
            name='user',
        ),
    ]
