# Generated by Django 5.1.2 on 2025-03-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_remove_ytrextrapay_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytrextrapay',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
