# Generated by Django 5.1.2 on 2025-03-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_ytrextrapay_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='refund',
            field=models.CharField(choices=[('Requested', 'requested'), ('Rejected', 'rejected'), ('Refunded', 'Refunded')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='pay',
            name='refundendamount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='refundendtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
