# Generated by Django 5.1.5 on 2025-03-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_pay_refund_pay_refundendamount_pay_refundendtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='refundtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
