# Generated by Django 5.1.5 on 2025-03-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_pay_refundtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
